### ISSUE TITLE
Building the project how to get an account for the local nexus?

### ISSUE THREAD

**Issue by Jibbe23** [eRP-FD/erp-processing-context#1]
Hello,

i am trying to build this project and in your build description it says: "get an account for the local nexus https://nexus.epa-dev.net/repository/erp-conan-internal. Ask Bogdan."

How can i get an account to the local nexus or how can i contact Bogdan?

thanks in advance and best regards

**Comment by hattenbach** [comment]
thx, build descriptions have been updated
